### ISSUE TITLE
Убрать SHOW запросы из Query

### ISSUE THREAD

**Issue by max107** [studio107/Mindy#15]
По умолчанию логика yii, yii2 заключается в выполнении "на каждый чих" запросов на получение структуры таблицы. Я предлагаю эту логику убрать вообще, так как у нас структура бд по сути описана в модели и наоборот быть не может. Т.е. - в yii, yii2 ты руками описываешь бд, далее по бд создаешь модели. В Mindy ORM происходит наоборот, следовательно подобные запросы, я считаю, не нужны вообще.

@AlexandrGordeev @qantus что думаете?

**Comment by qantus** [comment]
Поддерживаю целиком и полностью. У нас логика совсем иная и нам это просто не надо.

**Comment by max107** [comment]
Не устранены запросы в insert, update

**Comment by max107** [comment]
Выполнено в версии [1.2](https://github.com/MindyPHP/Mindy_Orm/releases/tag/1.2)
