### ISSUE TITLE
composer problem on ubuntu 14.04

### ISSUE THREAD

**Issue by kvashonin** [studio107/Mindy#16]
composer install --no-dev
Loading composer repositories with package information
Installing dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package mindy/query could not be found in any version, there may be a typo in the package name.
  Problem 2
    - Installation request for mindy/orm 0.1 -> satisfiable by mindy/orm[0.1].
    - mindy/orm 0.1 requires mindy/query 0.1 -> no matching package found.
  Problem 3
    - Installation request for mindy/controller 0.1 -> satisfiable by mindy/controller[0.1].
    - mindy/controller 0.1 requires mindy/base 0.2 -> no matching package found.
  Problem 4
    - mindy/orm 0.1 requires mindy/query 0.1 -> no matching package found.
    - mindy/tests 0.1 requires mindy/orm \* -> satisfiable by mindy/orm[0.1].
    - Installation request for mindy/tests 0.1 -> satisfiable by mindy/tests[0.1].

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by max107** [comment]
`cat composer.json`?

**Comment by kvashonin** [comment]
``` json
{
    "name": "mindy/one",
    "homepage": "http://studio107.ru",
    "version": "0.7",
    "type": "library",
    "license": "BSD-3-Clause",
    "autoload": {
        "psr-0": {
            "": "src/"
        }
    },
    "config": {
        "cache-files-ttl": 0
    },
    "require": {
        "php": ">=5.4",
        "mindy/orm": "0.1",
        "mindy/query": "0.9.2",
        "mindy/cache": "0.1",
        "mindy/base": "0.1",
        "mindy/form": "0.1",
        "mindy/pagination": "0.1",
        "mindy/finder": "0.1",
        "cebe/markdown": "*",
        "monolog/monolog": "1.10.0",
        "raven/raven": "0.9.0",
        "mindy/router": "0.1",
        "mindy/mail": "0.1",
        "mindy/storage": "0.1",
        "imagine/imagine": "v0.5.0",
        "mindy/update": "0.1",
        "mindy/template": "1.0.3",
        "mindy/console": "0.1",
        "mindy/controller": "0.1",
        "mindy/security": "0.1",
        "mindy/session": "0.1",
        "mindy/event": "0.1",
        "frandieguez/panorama-php": "1.0.7",
        "mindy/application": "0.1",
        "mindy/tests": "0.1",
        "mindy/table": "0.2.2"
    },
    "require-dev": {
        "phpunit/phpunit": "3.7.32",
        "phpunit/php-invoker": "1.1.3",
        "phpunit/dbunit": "1.3.1",
        "phpunit/phpunit-selenium": "1.3.3",
        "phpunit/phpunit-story": "1.0.2",
        "satooshi/php-coveralls": "dev-master"
    },
    "authors": [{
        "name": "Maxim Falaleev",
        "email": "max@studio107.ru",
        "homepage": "http://studio107.ru",
        "role": "Developer"
    }]
}
```

**Comment by max107** [comment]
Измени `query` на `0.3` версию
