### ISSUE TITLE
composer.json

### ISSUE THREAD

**Issue by kvashonin** [studio107/Mindy#2]
исправить dev зависимости в composer.json
выдает ошибку при установке:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpunit/php-invoker 1.1.3 -> satisfiable by phpunit/php-invoker[1.1.3].
    - phpunit/php-invoker 1.1.3 requires ext-pcntl \* -> the requested PHP extension pcntl is missing from your system.

**Comment by max107** [comment]
https://github.com/studio107/Mindy_Docs/commit/03d51f62d9801756f23fa6de21b07958cda8dc24
