### ISSUE TITLE
Проблема с with()

### ISSUE THREAD

**Issue by mirkoles** [studio107/Mindy#20]
Есть модель "Шина" с ForeignField "model_tyre" до модели "Модель шины" (мета-товар)

При простом запросе `Tyre::objects()->with(['model_tyre'])->asArray()->all()` - модели шин есть в результатах, но если попробовать сделать фильтрацию по полям модели ModelTyre (`Tyre::objects()->filter([''model_tyre__name' => 'Nordman'])->asArray()->all()` ), то модели шин отсутствуют в выборке.

**Comment by max107** [comment]
@mirkoles подскажите пожалуйста какая версия ORM и Query? Если установлены из `git`, то последний коммит. Если из composer то просто версии из composer.json в каждом из пакетов.

**Comment by mirkoles** [comment]
Query 0.1, ORM 0.1

**Comment by max107** [comment]
Попробуйте воспроизвести проблему с Orm 0.9.4, Query 0.3.

**Comment by mirkoles** [comment]
Проблема присутствует

**Comment by max107** [comment]
@mirkoles исправлено в ветке [fix_74](https://github.com/studio107/Mindy_Orm/tree/fix_74). Проверите?

**Comment by mirkoles** [comment]
Проблема осталась

**Comment by max107** [comment]
Я тогда не понимаю сути проблемы

``` php
    public function testIssue20()
    {
        $qs = User::objects()->with(['addresses'])->asArray();
        $this->assertEquals([
            [
                'customer' => [
                    'id' => 1,
                    'user_id' => 1,
                    'address' => 'address'
                ],
                'id' => 1,
                'username' => 'foo',
                'password' => '',
                'user_id' => 1
            ],
            [
                'customer' => [
                    'id' => null,
                    'user_id' => null,
                    'address' => ''
                ],
                'id' => 2,
                'username' => 'bar',
                'password' => '',
                'user_id' => ''
            ]
        ], $qs->all());
        $qs = User::objects()->filter(['addresses__address' => 'address'])->with(['addresses'])->asArray();
        $this->assertEquals([
            [
                'customer' => [
                    'id' => 1,
                    'user_id' => 1,
                    'address' => 'address'
                ],
                'id' => 1,
                'username' => 'foo',
                'password' => '',
                'user_id' => 1
            ]
        ], $qs->all());
    }
```

**Comment by max107** [comment]
В вашем примере 

``` php
Tyre::objects()->filter(['model_tyre__name' => 'Nordman'])->asArray()->all()
```

отсутствует `with`, следовательно, связанные записи будут отсутствовать в выборке. Это логично и корректно.

**Comment by mirkoles** [comment]
with забыл указать тут, на деле он присутствует: 

``` php
$filter = ['model_tyre__name' => 'Nordman 4'];
$qs = self::objects()->getQuerySet()->filter($filter);
$data = $qs->with(['model_tyre'])->asArray()->all();
```

$data без связанных записей :(

**Comment by mirkoles** [comment]
self == Tyre

**Comment by max107** [comment]
Может быть я что то не понимаю? =) Смотрим [testIssue20_2](https://github.com/studio107/Mindy_Orm/blob/252288aba7fbba99bf5bb634223a54caa10f5915/Tests/Cases/Orm/Issues/Issue20Test.php)

Единственная проблема которую я здесь вижу, это `model_tyre` != `modeltyre`

**Comment by max107** [comment]
@mirkoles я предлагаю перенести общение в irc, чтобы детально разобраться с этой проблемой. Канал в irc добавлен в readme

**Comment by mirkoles** [comment]
Всё, проблема нашлась. QuerySet использовался до получения данных. $qs->max('price'), поэтому with не отрабатывал.

**Comment by max107** [comment]
@mirkoles спасибо за помощь. В любом случае приглашаю в irc, так как документация по системе находится в разработке, смогу помогать.

**Comment by max107** [comment]
@mirkoles исправлено не корректное возвращение ключа связанной записи [75](https://github.com/studio107/Mindy_Orm/issues/75)
