### ISSUE TITLE
Storage useMD5

### ISSUE THREAD

**Issue by mirkoles** [studio107/Mindy#21]
При использовании md5 невозможно получить корректные ресайзы изображений

**Comment by max107** [comment]
@mirkoles сходу не сказать, но напоминает мне старую (уже решенную) проблему. Можете привести пример?

**Comment by mirkoles** [comment]
Файл в БД:
Mir/ModelTyre/2015-02-14/b198b50345c22620b66163ff0f0208e4_0.jpg

При попытке получить файл ресайза "preview":
Mir/ModelTyre/2015-02-14/preview_b198b50345c22620b66163ff0f0208e4_0.jpg

Хотя на диске лежит файл ресайза:
Mir/ModelTyre/2015-02-14/71d283e4eca4c96590e1b32a273b4c56_0.jpg

**Comment by max107** [comment]
@mirkoles Да, выглядит как старая проблема. Как вариант вы можете обновить все пакеты, к примеру так:
- Удаляем директорию `vendor`
- Скачиваем последний [composer.json](https://github.com/studio107/Mindy/blob/master/app/composer.json)
- Выполняем `composer install`

Либо

Скачиваем готовый пре-релиз из https://github.com/studio107/Mindy/releases и заменить директорию vendor.

Единственная нарушенная обратная совместимость - формирование роутов через `:` вместо `.`.

Раньше `$urlManager->reverse('my_module_namespace.my_route')`, сейчас `$urlManager->reverse('my_module_namespace:my_route')`

**Comment by mirkoles** [comment]
Обновил, но проблема осталась.

**Comment by mirkoles** [comment]
А так же, когда не используется md5 пути до файлов выглядят следующим образом: Mir/ModelTyre/2015-02-14/Mir/ModelTyre/2015-02-14/Freeze_Avatyre_0.jpg

**Comment by max107** [comment]
@mirkoles понял. Постараюсь воспроизвести и исправить в течении 1-2 часов. Как временное решение выводить превью не по префиксу `url_preview` а по размеру `url_200x200`.

**Comment by mirkoles** [comment]
Даже так не работает :( + надо работать с ресайзами в формате asArray, так как данных на странице может быть до 1000-1500

**Comment by max107** [comment]
Странное желание выводить разом на одной странице 1000 товаров. Но все же, я понял. Работа с ресайзами при `asArray` будет реализована, но было бы не плохо обсудить интерфейс.

**Comment by mirkoles** [comment]
Подразумевается, что 1500 - это максимальное значение, реальные значения будут в пределах 100. А ресайзы можно было бы на лету через расширение шаблонизатора строить, просто подставляя нужный префикс к файлу :)

**Comment by max107** [comment]
Преждевременная оптимизация - корень всех бед =)

100 на странице можно выводить без `asArray`, это не составляет проблемы. Тем более можно использовать [endless](https://github.com/studio107/Mindy/blob/master/www/static/js/endless_on_scroll.js) постраничную разбивку.

Расширение шаблонизатора это добро, но в него так или иначе нужно будет передать
- Или экземпляр класса модели для составления корректного пути по имени модуля и имени модели
- Или передавать имя модуля и модели самостоятельно

**Comment by max107** [comment]
Предлагаемый синтаксис:

``` twig
{% image data.image model %}
```

где `model` экземпляр класса модели. Или

``` twig
{% image data.image modelName moduleName %}
```

@qantus @AlexandrGordeev ?

**Comment by qantus** [comment]
У нас уже хранится путь до картинки (оригинала) в БД, например:

```
Mir/ModelTyre/2015-02-22/2dec59df420e434ae2b0161c8b2d5d52_0.jpg
```

Резайз лежит там же, где и само изображение, исходя из этого можно просто перед именем файла подставлять нужный ресайз. Условно, вот так:

```
Mir/ModelTyre/2015-02-22/{{ resize_name }}2dec59df420e434ae2b0161c8b2d5d52_0.jpg
```

И мы получим путь до уменьшенного изображения.

**Comment by max107** [comment]
``` twig
{% image data.my_image_url 'my_prefix' %}
```
