### ISSUE TITLE
Проблемы с выборкой при удалении

### ISSUE THREAD

**Issue by mirkoles** [studio107/Mindy#25]
При попытке удаления данных, фильтрация(исключение) по связанным данным не работает,
в итоге не создается "JOIN"

``` php
public function cleanOldTyres()
    {
        $storage = Storage::byKey($this->keyStorage);
        AvailTyre::objects()->filter(['storage'=>$storage])->exclude([
            'tyre__in' => $this->collectedTyres,
            'tyre__model_tyre__season'=>ModelTyre::SEASON_WINTER
        ])->delete();
    }
```

**Comment by max107** [comment]
Дай вывод 

``` php
...->deleteSql();
```

Пожалуйста

**Comment by qantus** [comment]
Модель: 

``` php
class Event extends Model
{
    public static function getFields() 
    {
        return [
            'place' => [
                'class' => ForeignField::className(),
                'modelClass' => Place::className(),
                'verboseName' => TourModule::t('Place')
            ],
            'datetime' => [
                'class' => DatetimeField::className(),
                'verboseName' => TourModule::t('Datetime')
            ]
        ];
    }
}
```

Place:

``` php
class Place extends Model
{
    public static function getFields() 
    {
        return [
            'name' => [
                'class' => CharField::className(),
                'verboseName' => TourModule::t('Name')
            ],
            'position' => [
                'class' => IntField::className(),
                'editable' => false,
                'default' => 9999,
                'null' => true
            ],
        ];
    }
}
```

Выполняем: 

``` php
Event::objects()->filter(['place__name' => ''])->deleteSql();
```

Получаем:

``` sql
DELETE FROM `tour_event` WHERE (`name`='')
```

**Comment by max107** [comment]
Так как sql не поддерживает `JOIN` в `DELETE FROM` а строить под запросы не совсем понятно по какому алгоритму, особенно с учетом разного синтаксиса разных субд (вмешиваться в запрос плохо), было принято решение вызывать `exception` в случаях когда при удалении используется фильтрация по связям.

Решение:

``` php
$storage = Storage::byKey($this->keyStorage);
$pkList = AvailTyre::objects()->filter(['storage'=>$storage])->exclude([
    'tyre__in' => $this->collectedTyres,
    'tyre__model_tyre__season'=>ModelTyre::SEASON_WINTER
])->valuesList('pk', true);
AvailTyre::objects()->filter(['pk__in' => $pkList])->delete();
```

С другой стороны, можно определить подобные запросы и выполнить тот же код с `valuesList('pk', true)` и `filter` внутри метода `delete`. Кто что думает?

Если есть другое решение или предложение - пожалуйста предлагайте.

@qantus @mirkoles @AlexandrGordeev

**Comment by max107** [comment]
Первый вариант решения - exception: https://github.com/studio107/Mindy_Orm/commit/1904403b70f7a80387d4df700ee2f0ba0f5af288

Второй вариант решения - неявное выполнение `valuesList('pk', true)` и запроса `where in`:

``` php
        $tableName = $this->model->tableName();

        if ($this->filterHasJoin()) {
            $this->prepareConditions();
            return $this->createCommand()->delete($tableName, [
                $this->retreivePrimaryKey() => $this->valuesList(['pk'], true)
            ], $this->params);
        } else {
            $this->prepareConditions(false);
            return $this->createCommand()->delete($tableName, $this->where, $this->params);
        }
```

https://github.com/studio107/Mindy_Orm/commit/b32b3a9f7bb556f219c935d9ea9f3f5cf46d5543

Ваши мысли, господа?

**Comment by AlexandrGordeev** [comment]
exception мне кажется лучше неявного выполнения кода

**Comment by qantus** [comment]
exception - дальше уже дело разработчика.

**Comment by max107** [comment]
Я все же останавливаюсь на варианте с неявным под запросом. С точки зрения ORM если возможно выполнение `filter(...)->delete()`, значит код должен работать очевидно, т.е. удалять выбранные записи.

**Comment by max107** [comment]
Вопрос открыт до реализации поддержки составного ключа
