### ISSUE TITLE
Проблема с ресайзом изображения

### ISSUE THREAD

**Issue by mirkoles** [studio107/Mindy#26]
в модели описано изображение

``` php
"logo" => [
      "class" => ImageField::className(),
      "verboseName" => "Логотип",
      'sizes' => [
              'preview' =>[
                      187,187,
                      'method'=> 'resize'
              ]
      ]
]
```

При обращении по URL самого изображения картинка доступна, 
при обращении к ресайзу получаем
Mindy\Exception\HttpException

```
Невозможно обработать запрос "/media/Mir/ProducerWheel/2015-02-23/preview_818744b64dd319add77a2db966ac3e8a_0.png".
```

**Comment by mirkoles** [comment]
Если обратиться к ресайзу кодом (например {{model.logo.url_preview }})  ресайз создается, до этого обращения он отсутствует на диске

**Comment by max107** [comment]
@mirkoles исправлено в https://github.com/studio107/Mindy_Orm/commit/39b550d69e58067f4d4170fc65e12ac272ba70e6

Нужно обновить `orm`, `storage`. Исправленой версии в `composer` пока нет.
