### ISSUE TITLE
Request->redirect ()

### ISSUE THREAD

**Issue by tsukasa-mixer** [studio107/Mindy#30]
Местами в коде используется $request->getPath()
в классе он берется из Request->__requestUri

в функции public function redirect($url, $data = [], $statusCode = 302) 
данное поле не заполняется новым значением, если ничто не перехватит запрос то проблемы не будет.
Однако в  MiddleWare если будет перекрыватся то урл вернет не корректный, и вместо редиректа мы получим рефреш 

предлагаю функцию описать так

``` php
public function redirect($url, $data = [], $statusCode = 302)
    {
        if (is_object($url) && $url instanceof \Mindy\Orm\Model && method_exists($url, 'getAbsoluteUrl')) {
            $url = $url->getAbsoluteUrl();
        }
        if(strpos($url, '/') === false) {
            $url = Mindy::app()->urlManager->reverse($url, $data);
        }

        $this->_requestUri = $url; // сохраняем новый url

        header('Location: ' . $url, true, $statusCode);
        $app = Mindy::app();
        if($app->hasComponent('middleware')) {
            $app->middleware->processResponse($app->getComponent('request'));
        }

        die();
    }
```

**Comment by max107** [comment]
По логике находясь на `/foo/bar/` и выполняя редирект - текущий урл `/foo/bar/` и меняться он не должен. После редиректа урл изменится на `/foo/something/` и так же меняться не должен.

Оно не просто так `private $_requestUri;`

**Comment by tsukasa-mixer** [comment]
@max107 ок, значит в мидлвари неправильно получается путь куда следует уйти.

**Comment by max107** [comment]
@tsukasa-mixer по логике вещей, получать путь и переопределять редирект не нужно, так как он был выставлен ранее функцией `redirect()` в классе `Http`. Следовательно нужно заменить только статус код.

Для теста:

``` php
<?php

namespace Mindy\Middleware;

use Mindy\Http\Request;

/**
 * Class AjaxRedirectMiddleware
 * @package Mindy\Middleware
 */
class AjaxRedirectMiddleware extends Middleware
{
    public function processResponse(Request $request)
    {
        if ($request->getIsAjax() && in_array($request->getStatusCode(), [301, 302])) {
            header("HTTP/1.1 278 OK", true, 278);
        }
    }
}

```

**Comment by tsukasa-mixer** [comment]
@max107 В конкретном случае - верно, как-бы нас только код ответа тут интересует.

**Comment by qantus** [comment]
@max107 @tsukasa-mixer проблема актуальна еще?

**Comment by max107** [comment]
@qantus нет. В данный момент проблема решена без рефакторинга `Request`. В перспективе его все равно придется переписывать как минимум по причине совместимости с PSR-7.
