### ISSUE TITLE
Пачка мелких багов.

### ISSUE THREAD

**Issue by tsukasa-mixer** [studio107/Mindy#34]
- MenuAdmin: отсутсвует `$linkColumn = 'name'`
- Mindy_Form:  `$item = $event->getLast()->value;`, `$event->getLast()` не всегда что-то вернет.
- MetaAdmin:`getColumns()`, `'id'` - Лишнее
- Faq: требуется обновить модуль
- Reviews: Требуется обновить модуль

**Comment by max107** [comment]
@tsukasa-mixer 

> Mindy_Form: $item = $event->getLast()->value;, $event->getLast() не всегда что-то вернет.

?

**Comment by max107** [comment]
Проблема с событием была в связи с пустым файлом `config/events.php`.
