### ISSUE TITLE
Несколько модулей, начинающихся с корня в роутах

### ISSUE THREAD

**Issue by qantus** [studio107/Mindy#51]
Суть проблемы: у нас есть 3 модуля, все роуты которых должны начинаться от корня: каталог, основной модуль с главной страницей и контактами и модуль динамических страниц. Каталог имеет урлы вида "/beds", "/mats" (их ограниченное фиксированное количество), Страницы имеют урлы вида "/news", "/articles" (их неограниченное динамическое количество), Главный модуль имеет страницы вида "/" (главная), "/contacts". Если у нас 2 модуля то проблему можно решить вот так:

``` php
[
...
    '' => new Patterns('Modules.Catalog.urls', 'catalog'),
    '/' => new Patterns('Modules.Pages.urls', 'page'),
...
]
```

А вот когда 3 - тогда так уже не выкрутится. Вариант решения - сделать как в джанге (массив с массивами). Адово, конечно, но гибкость повышается. Может быть есть еще какие варианты у кого?

**Comment by tsukasa-mixer** [comment]
Имхо тогда вероятно местами будет проще придти к реализации сборки всех динамических урлов в 1 таблицу и рулить исходя из него. правда не уверен в красивости данного варианта.

**Comment by max107** [comment]
Поддержка реализована. Новый синтаксис выглядит так:

``` php
return [
    ['route' => '/foo/bar', 'handler' => callable]
];
```
