### ISSUE TITLE
Нельзя изменить размеры таблицы.

### ISSUE THREAD

**Issue by MaksimMalashkin** [studio107/Mindy#55]
Создал таблицу 3х3, сохранил страницу. Таблица по ширине получается больше экрана.

**Comment by max107** [comment]
Как временное решение проблемы попробуй изменить следующее:

![cttrar7lmc](https://cloud.githubusercontent.com/assets/862272/9831410/6abb684a-595f-11e5-8cc3-ab5363d2c210.gif)

**Comment by MaksimMalashkin** [comment]
Большое спасибо.
