### ISSUE TITLE
Востребованость afterAction и beforeAction в контроллерах

### ISSUE THREAD

**Issue by max107** [studio107/Mindy#59]
@MindyPHP/collaborators Вопрос востребованости `afterAction` и `beforeAction` в контроллерах. В планах удалить эти события.

Обратная совместимость: в местах где нужны данные события их можно определить самостоятельно и использовать как нужно.

**Comment by tsukasa-mixer** [comment]
Если описать реализацию данных событий в примерах, то явной необходимости в них не вижу.

**Comment by qantus** [comment]
Так же поддержу, если примеры будут :) Нужны, но редко и как события (чем они и являются) они выглядят более чем логично.
