### ISSUE TITLE
Версионность пакетов composer

### ISSUE THREAD

**Issue by max107** [studio107/Mindy#60]
@MindyPHP/collaborators Версионность пакетов сomposer будет изменена. Упраздится `version` из `composer.json` и вся версионность будет основана на тегах гита. Так же будут убраны все зависимости пакетов кроме версии php, кроме пакета mindy который будет содержать в себе полный список зависимостей с версиями.

**Comment by qantus** [comment]
То есть пакеты друг от друга фактически зависеть не будут? Чтобы коллизий не было?

**Comment by tsukasa-mixer** [comment]
@qantus да, сейчас из-за имеющихся связей компосер тупит, если гдет связь не обновили - все, пакеты обновлены не будут или будут автоматом downgrade

**Comment by qantus** [comment]
Ага, я в курсе. Жутко неудобно. Поддерживаю!

**Comment by max107** [comment]
Ок, принято.
