### ISSUE TITLE
Изображения и watermark

### ISSUE THREAD

**Issue by tsukasa-mixer** [studio107/Mindy#67]
Замечены следующий поведения.
- если ватермарк больше накладываемого изображения - оно не накладывается (думаю хотя-бы для режима наложения center имеет смысл делать ресайз ватермарка)
- если указан ватермарк глобальный, то он накладывается на большое изображение и **не** накладывается на preview изображение, т.е. для preview нужно получается указывать watermark своих размеров

и дополнительно предложение, добавить режим наложения адаптивного размера, когда заливается огромный ватермарк который уменьшается до нужных размеров основного изображения и накладывается по центру, это наиболее часто нужное действие.

**Comment by max107** [comment]
https://github.com/MindyPHP/Mindy_Orm/pull/140
